### ISSUE TITLE
Run protocol on desktop bpod rig

### ISSUE THREAD

**Issue by ckarageorgkaneen** [HenryJFlynn/mouse2afc#10] opened 2023-05-17 08:19 UTC
This issue likely too large. can split into smaller issue later. Those being
1. `['stderr', '2023-06-12 10:17:08.224305', '', '[Errno 98] Address already in use', '', '']` got this after messing with the arduino software then trying to run pybpod on emulator mode.
2. https://github.com/HenryJFlynn/mouse2afc/issues/10#issuecomment-1586850437

**Comment by HenryJFlynn** [comment] 2023-06-09 08:55
^ stuff with arduino. I needed to download the firmware files from sanworks and upload them to the device. Matlab is working fine. Pybpod pop this error:
```python
Error: Future firmware detected. Please update the Bpod python software.
```

**Comment by HenryJFlynn** [comment] 2023-06-12 06:30
^^ how to update the [firmware](https://pybpod.readthedocs.io/projects/pybpod-api/en/v1.8.1/getting_started/firmware_update.html)

**Comment by HenryJFlynn** [comment] 2023-06-12 08:34
^^ fixed. In the arduino code change the firmware and machine to fit that of the device

**Comment by HenryJFlynn** [comment] 2023-06-12 08:35
new problem: the lights are not lighting up on the device

**Comment by HenryJFlynn** [comment] 2023-06-16 12:45
> ^ stuff with arduino. I needed to download the firmware files from sanworks and upload them to the device. Matlab is working fine. Pybpod pop this error:
> 
> ```python
> Error: Future firmware detected. Please update the Bpod python software.
> ```

In the api, `bpod_base.py` : 
```python
#########################################################
        ### check the firmware version ##############################
        #########################################################
        firmware_version, machine_type = self._bpodcom_firmware_version()

        if firmware_version < int(settings.TARGET_BPOD_FIRMWARE_VERSION):
            raise BpodErrorException('Error: Old firmware detected. Please update Bpod 0.7+ firmware and try again.')

        if firmware_version > int(settings.TARGET_BPOD_FIRMWARE_VERSION):
            raise BpodErrorException('Error: Future firmware detected. Please update the Bpod python software.')

        self._hardware.firmware_version = firmware_version
        self._hardware.machine_type = machine_type
```

Does this mean that the firmware can ONLY be equal to the target firmware?

**Comment by HenryJFlynn** [comment] 2023-06-16 12:48
^ Fixed. Going into user settings and changing the firmware to equal 22 allowed the `Load Board Info` button work

**Comment by HenryJFlynn** [comment] 2023-06-16 12:57
^^ residual from creating the trials class. `self.MT` should be `self.Trials.MT`

**Comment by HenryJFlynn** [comment] 2023-06-16 13:03
^^ `PerfL = 1 - (sum(ndxRightRewd) / (LAST_TRIALS * 2))` this breaks because `ndxRightRewd` is a list of `True` or `false`. I believe this is an error when copying matlab because matlab uses 1's and 0's

**Comment by HenryJFlynn** [comment] 2023-06-16 13:29
See https://github.com/HenryJFlynn/mouse2afc/issues/27 for the fix

**Comment by HenryJFlynn** [comment] 2023-06-28 11:13
The protocol pops no errors now. The problem is that the set up does not seem to be getting or giving any information. The lights to not light up and the pokes do not work.

**Comment by HenryJFlynn** [comment] 2023-06-28 11:24
I have been running the protocol with `emulator_mode = True` still which is incorrect. When it is false, initially it works, i can select settings but once it tries to run I get this error: 
```python
['stderr', '2023-06-28 14:02:58.931788', '', 'Traceback (most recent call last):\n', '', '']
['stderr', '2023-06-28 14:02:58.932031', '', '  File "/home/henry/Documents/pybpod-project/tasks/emulator_mouse2afc_example/emulator_mouse2afc_example.py", line 8, in <module>\n', '', '']
['stderr', '2023-06-28 14:02:58.932363', '', '    ', '', '']
['stderr', '2023-06-28 14:02:58.932436', '', 'Mouse2AFC(bpod).run()', '', '']
['stderr', '2023-06-28 14:02:58.932489', '', '\n', '', '']
['stderr', '2023-06-28 14:02:58.932542', '', '  File "/home/henry/Documents/mouse2afc/mouse2afc.py", line 45, in run\n', '', '']
['stderr', '2023-06-28 14:02:58.932733', '', '    ', '', '']
['stderr', '2023-06-28 14:02:58.932796', '', 'if not self._bpod.run_state_machine(sma):', '', '']
['stderr', '2023-06-28 14:02:58.932848', '', '\n', '', '']
['stderr', '2023-06-28 14:02:58.932900', '', '  File "/home/henry/Documents/chris-pybpod/base/pybpod-api/pybpodapi/bpod/bpod_base.py", line 288, in run_state_machine\n', '', '']
['stderr', '2023-06-28 14:02:58.933182', '', '    ', '', '']
['stderr', '2023-06-28 14:02:58.933244', '', "raise BpodErrorException('Error: The last state machine sent was not acknowledged by the Bpod device.', self)", '', '']
['stderr', '2023-06-28 14:02:58.933299', '', '\n', '', '']
['stderr', '2023-06-28 14:02:58.933358', '', 'pybpodapi.exceptions.bpod_error', '', '']
['stderr', '2023-06-28 14:02:58.933484', '', '.', '', '']
['stderr', '2023-06-28 14:02:58.933545', '', 'BpodErrorException', '', '']
['stderr', '2023-06-28 14:02:58.933607', '', ': ', '', '']
['stderr', '2023-06-28 14:02:58.933656', '', "('Error: The last state machine sent was not acknowledged by the Bpod device.', <pybpodapi.bpod.Bpod object at 0x7f294ec64dd8>)", '', '']
['stderr', '2023-06-28 14:02:58.933710', '', '\n', '', '']
```

**Comment by HenryJFlynn** [comment] 2023-06-28 11:52
> The protocol pops no errors now. The problem is that the set up does not seem to be getting or giving any information. The lights to not light up and the checks are not checked

The problem may have been the firmware. Using the firmware provide by Sanworks (which is the one that works with matlab). The lights now light up but they checks do not.

**Comment by HenryJFlynn** [comment] 2023-06-28 12:58
It is questionable if the checks are suppose to become checked. I have sent an email to the Champalimaud Foundation about it.

**Comment by HenryJFlynn** [comment] 2023-07-10 14:20
> It is questionable if the checks are suppose to become checked. I have sent an email to the Champalimaud Foundation about it.

They answered, this functionality does NOT exist. We will have to make it if we want it

**Comment by HenryJFlynn** [comment] 2023-07-26 12:47
Pybpod works on the desktop rig which I have but this setup does not have everything I need to fully test the software. Only two of the lights work and none of the pokes work, nor do the valves and there are no speakers. I will have to test Pybpod on a functional setup which is used for experimentation to fully test the software. \

Because of this I will close this issue for now and open a new one for testing the software on the actual experimental setup

**Closed by HenryJFlynn** 2023-07-26 12:47 UTC
Labels: bug, enhancement
